# Generated by Django 4.2.4 on 2023-11-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('IdApuesta', models.AutoField(primary_key=True, serialize=False)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FechaApuesta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('idDeporte', models.AutoField(primary_key=True, serialize=False)),
                ('Deporte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoApuesta',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('DescripcionTipo', models.CharField(max_length=100)),
                ('idApuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.apuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('idParticipante', models.AutoField(primary_key=True, serialize=False)),
                ('NombreParticipante', models.CharField(max_length=100)),
                ('idDeporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEvento', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('EstadoEvento', models.CharField(choices=[('FUTURO', 'Futuro'), ('ACTIVO', 'Activo'), ('TERMINADO', 'Terminado')], default='FUTURO', max_length=10)),
                ('idDeporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.deporte')),
            ],
        ),
        migrations.AddField(
            model_name='apuesta',
            name='IdUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.usuario'),
        ),
        migrations.CreateModel(
            name='ApuestaEvento',
            fields=[
                ('idApuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Principal.apuesta')),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EstadoEvento', models.CharField(choices=[('FUTURO', 'Futuro'), ('ACTIVO', 'Activo'), ('TERMINADO', 'Terminado')], default='FUTURO', max_length=10)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.evento')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.tipoapuesta')),
            ],
        ),
    ]
