# Generated by Django 4.2.4 on 2023-11-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_remove_usuario_nombre_usuario_apellido_materno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apuesta',
            old_name='FechaApuesta',
            new_name='fecha_apuesta',
        ),
        migrations.RenameField(
            model_name='apuesta',
            old_name='IdApuesta',
            new_name='id_apuesta',
        ),
        migrations.RenameField(
            model_name='apuesta',
            old_name='IdUsuario',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='apuesta',
            old_name='Monto',
            new_name='monto',
        ),
        migrations.AddField(
            model_name='apuesta',
            name='nombre_apuesta',
            field=models.CharField(default='', max_length=100),
        ),
    ]
