# Generated by Django 4.2.4 on 2023-11-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_rename_fechaapuesta_apuesta_fecha_apuesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
