# Generated by Django 4.2.4 on 2023-11-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0004_remove_usuario_contraseña_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apuestaevento',
            old_name='idApuesta',
            new_name='id_apuesta',
        ),
        migrations.RenameField(
            model_name='apuestaevento',
            old_name='idEvento',
            new_name='id_evento',
        ),
        migrations.RenameField(
            model_name='apuestaevento',
            old_name='idTipo',
            new_name='id_tipo',
        ),
        migrations.RenameField(
            model_name='apuestaevento',
            old_name='Monto',
            new_name='monto',
        ),
        migrations.RenameField(
            model_name='deporte',
            old_name='Deporte',
            new_name='deporte',
        ),
        migrations.RenameField(
            model_name='deporte',
            old_name='idDeporte',
            new_name='id_deporte',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='idDeporte',
            new_name='id_deporte',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='idEvento',
            new_name='id_evento',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='NombreEvento',
            new_name='nombre_evento',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='idDeporte',
            new_name='id_deporte',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='idParticipante',
            new_name='id_participante',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='NombreParticipante',
            new_name='nombre_participante',
        ),
        migrations.RenameField(
            model_name='tipoapuesta',
            old_name='DescripcionTipo',
            new_name='descripcion_tipo',
        ),
        migrations.RenameField(
            model_name='tipoapuesta',
            old_name='idApuesta',
            new_name='id_Apuesta',
        ),
        migrations.RemoveField(
            model_name='tipoapuesta',
            name='idTipo',
        ),
        migrations.AddField(
            model_name='tipoapuesta',
            name='id_tipo',
            field=models.IntegerField(default=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
