# Generated by Django 4.2.4 on 2023-11-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0005_rename_idapuesta_apuestaevento_id_apuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
