# Generated by Django 4.2.4 on 2023-12-07 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0007_apuesta_descripcion_apuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuestatenis',
            fields=[
                ('id_apuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apuesta', models.CharField(default='', max_length=100)),
                ('descripcion_apuesta', models.CharField(default='', max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_apuesta', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Apuestabasket',
            fields=[
                ('id_apuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apuesta', models.CharField(default='', max_length=100)),
                ('descripcion_apuesta', models.CharField(default='', max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_apuesta', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.usuario')),
            ],
        ),
    ]
